# Generated by Django 5.2.7 on 2025-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_dashboardwidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('camera', 'Camera'), ('thermostat', 'Thermostat'), ('light', 'Smart Light'), ('lock', 'Smart Lock'), ('speaker', 'Smart Speaker'), ('hub', 'IoT Hub'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20),
        ),
    ]
